[book]
authors = ["renoise"]
language = "en"
multilingual = false
src = "docs"
title = "Renoise Scripting"

[build]
create-missing = false

[output.html]
default-theme = "dark"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/renoise/xrnx"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/renoise/xrnx/edit/master/{path}"
additional-css = [ "docs/styles.css" ]

[output.linkcheck]
warning-policy = "ignore"

[preprocessor.toc]
[preprocessor.alerts]