[book]
authors = ["renoise"]
language = "en"
src = "docs"
title = "Renoise Scripting"

[build]
create-missing = false

[output.html]
default-theme = "dark"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/renoise/xrnx"
edit-url-template = "https://github.com/renoise/xrnx/edit/master/{path}"
additional-css = [ "docs/styles.css" ]
sidebar-header-nav = false

