[book]
authors = ["renoise"]
language = "en"
multilingual = false
src = "docs"
title = "Renoise Scripting"

[build]
create-missing = false

[output.html]
default-theme = "dark"
preferred-dark-theme = "coal"

#[output.linkcheck]
#warning-policy = "ignore"