[book]
authors = ["renoise"]
language = "en"
multilingual = false
src = "docs"
title = "Renoise Scripting"

[build]
create-missing = false

[output.html]
default-theme = "dark"
preferred-dark-theme = "ayu"
additional-css = [ "docs/styles.css" ]

[output.linkcheck]
warning-policy = "ignore"

[preprocessor.toc]
[preprocessor.alerts]