name: Build and Archive XRNX_Starter_Pack.zip

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
            
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install mdbook
        run: cargo binstall -y mdbook mdbook-linkcheck mdbook-toc mdbook-alerts

      - name: Build the API
        run: cargo run

      - name: Build the book
        run: mdbook build

      - name: Create XRNX_Starter_Pack
        run: |
          mkdir dist
          cp -rf definitions dist/definitions
          cp -rf book/html dist/docs
          cp -rf tools dist/tools
          rm -rf dist/*/.git dist/*/.gitignore
          echo -e '<html>\n<body>\n<script type="text/javascript">\n\twindow.location.href = "./docs/index.html";\n</script>\n</body>\n</html>' > dist/docs.html 
        
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: XRNX_Starter_Pack
          path: dist
