name: Build and Deploy mdBook

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v2
        with:
          cache-workspaces: "docs"
          cache-key: "renoise-xrnx"

      - name: Build the API
        run: cargo run

      - name: Install mdbook
        run: cargo install mdbook@^0.5

      - name: Build the book
        run: mdbook build

      - name: Validate links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --offline --root-dir "$GITHUB_WORKSPACE/book" book
          fail: true

      # the steps below only run on pushes to master, not on PRs
      
      - name: Create XRNX_Starter_Pack
        if: github.ref_name == 'master'
        run: |
          mkdir dist
          cp -rf definitions dist/definitions
          cp -rf book dist/docs
          cp -rf tools dist/tools
          rm -rf dist/*/.git dist/*/.gitignore
          echo -e '<html>\n<body>\n<script type="text/javascript">\n\twindow.location.href = "./docs/index.html";\n</script>\n</body>\n</html>' > dist/docs.html

      - name: Upload Archive
        uses: actions/upload-artifact@v4
        if: github.ref_name == 'master'
        with:
          name: XRNX_Starter_Pack
          path: dist

      - name: Upload Pages
        uses: actions/upload-pages-artifact@v5
        if: github.ref_name == 'master'
        with:
          name: github-pages
          path: ./book

  deploy:
    # Add a dependency to the build job
    needs: build
    if: github.ref_name == 'master'

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5 # or specific "vX.X.X" version tag for this action
